spring:
  application:
    name:
      s21Library_DBController
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    username: mynewuser
    password: mypassword
    url: jdbc:postgresql://91.186.197.234:5432/library
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: dev
server:
  port: 8083